name: Github Pages Deploy
on: 
  push: 
    branches: 
      -"master"

jobs: 
  build: 
    runs-on: ubuntu-latest

    strategy:
      matrix: 
        node-versions: [15.x]
    steps: 
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install and build 
        run: nom install && npm run build

      - name: Deploy
        uses: Ticodelico/github-pages-deploy-action@4.1.1
        with: 
          branch: gh-pages 
          folder: build